booklib/urls.py
from django.urls import path

from .views import get_main_page, get_new_book, get_new_person, give_book, get_bookobj, return_book, auth_user, get_data_person

urlpatterns = [
    path('', get_main_page, name='main'),
    path('add_book/', get_new_book, name='new_book'),
    path('add_person/', get_new_person, name='new_person'),
    path('give_book/', give_book, name='give_book'),
    path('give_book/get_bookobj/', get_bookobj, name='get_bookobj'),
    path('return_book/', return_book, name = 'return_book'),
    path('login/', auth_user, name='login'),
    path('give_book/get_data_person/', get_data_person, name='get_data'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('booklib.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booklib/models.py
from datetime import date

from django.core.validators import RegexValidator
from django.db import models
import uuid
from django.db.models import Sum



class Book(models.Model):
    '''Книги в библиотеке.'''
    rating_book = (
        (5, '5'),
        (4, '4'),
        (3, '3'),
        (2, '2'),
        (1, "\U00002605"),
    )
    title_rus = models.CharField('Наименование книги', max_length=200)
    title_orig = models.CharField('Наименование книги (ориг.)', max_length=200, null=True, blank=True)
    year = models.PositiveIntegerField('Год издания', null=True,blank=True)
    quantity_pages = models.PositiveIntegerField('Количество страниц',null=True,blank=True)
    rating = models.DecimalField('Общий рейтинг', max_digits=2, decimal_places=1, default=0)
    counter_rating = models.DecimalField('Счетчик рейтинга', max_digits=2, decimal_places=1, default=0, null=True, blank=True)
    return_rating = models.DecimalField('Рейтинг при возврате', max_digits=2, decimal_places=1, choices = rating_book, null=True, blank=True)
    general_quantity = models.IntegerField('Общее количество экземпляров', default=0, null=True, blank=True)
    current_quantity = models.IntegerField('Доступное количество экземпляров', null=True, blank=True)
    distrib_quantity = models.IntegerField('Количество выданных экземпляров', default=0, null=True, blank=True)
    genres = models.ManyToManyField('Genre')
    class Meta:
        verbose_name='Книга'
        verbose_name_plural='Книги'
        ordering = ['current_quantity', 'title_rus']

    def __str__(self):
        return f'{self.title_rus}, {self.year}'

    def count_rating(self):
        '''Расчитывает рейтин книгию'''
        self.rating = round((self.rating * self.counter_rating + self.return_rating) / ( self.counter_rating + 1 ), 1)
        return self.rating

    def update_general_quantity(self):
        '''Обновляет общее количество книг.'''
        self.general_quantity = self.general_quantity + 1
        return self.general_quantity

    def get_current_quantity(self):
        '''Определяет количество доступных книг.'''
        self.current_quantity = self.general_quantity - self.distrib_quantity
        return self.current_quantity


class BookObj(models.Model):
    '''Пул книг одного вида.'''
    coef = (
        (1, 'отличное'),
        (0.8, 'хорошее'),
        (0.6, 'удовлетворительное'),
        (0.4, 'неудовлетворительное'),
        (0.2, 'списание'),
    )
    registr_number = models.UUIDField('Регистрационный номер', primary_key=True, default=uuid.uuid4, editable=False, max_length=8)
    book = models.ForeignKey(Book, on_delete=models.PROTECT, verbose_name='Книга')
    registr_date = models.DateField('Дата регистрации', auto_now_add=True)
    price = models.DecimalField('Стоимость', max_digits=8, decimal_places=2)
    price_per_day = models.DecimalField('Цена за день', max_digits=5, decimal_places=2)
    current_day_price = models.DecimalField('Текущая цена за день', max_digits=5, decimal_places=2, null=True, blank=True)
    coefficient = models.DecimalField('Коэффициент', max_digits=2, decimal_places=1, choices=coef, default=1, null=True, blank=True)
    space = models.CharField('Место хранения', max_length=200, null=True, blank=True)
    status_book = models.BooleanField('Статус книги', default=False)
    return_order = models.ManyToManyField('ReturnB', verbose_name='Книги возврата')
    mark = models.BooleanField(default=False)

    class Meta:
        verbose_name='Экземпляр книги'
        verbose_name_plural='Экземпляры книг'

    def __str__(self):
        return f'{self.book.title_rus} {self.registr_number}'

    # def get_current_day_price(self):
    #     '''Определяет стоимость книги за день.'''
    #     self.current_day_price = round(float(self.price_per_day) * self.coefficient, 2)
    #     return self.current_day_price

    @property
    def current_final_price(self):
        '''Определяет остаточную стоимость книги'''
        return self.price * self.coefficient


class Genre(models.Model):
    '''Жанры книг.'''
    name_genre = models.CharField('Жанр', max_length=50, validators =[RegexValidator(regex='^[A-Za-zА-Яа-яЁё]+$', message='Введите только буквы.', code='invalid_name')])

    class Meta:
        verbose_name='Жанр книги'
        verbose_name_plural='Жанры книг'

    def __str__(self):
        return self.name_genre


class Author(models.Model):
    '''Авторы книг.'''
    books = models.ManyToManyField(Book)
    name = models.CharField('Автор', max_length=200, validators =[RegexValidator(regex='^[A-Za-zА-Яа-яЁё]+$', message='Введите только буквы.', code='invalid_name')])
    photo_author = models.ImageField('Фото авторов', upload_to='photo_author/', null=True, blank=True)

    class Meta:
        verbose_name='Автор книги'
        verbose_name_plural='Авторы книг'

    def __str__(self):
        return self.name


class FotoRegistr(models.Model):
    '''Фото обложки книги.'''
    books = models.ForeignKey(Book, on_delete=models.PROTECT)
    photo_book = models.ImageField('Фото обложки', upload_to='photo_book/')

    class Meta:
        verbose_name='Фотография обложки книги'
        verbose_name_plural='Фотографии обложки книг'

    def __str__(self):
        return f'Фото книги {self.books.title_rus}'

class FotoStatus(models.Model):
    '''Текущее состояние книги.'''
    book_obj = models.ForeignKey(BookObj, on_delete=models.PROTECT)
    photo_status = models.ImageField('Фото состояния книги', upload_to='photo_status/', null=True, blank=True)
    list_status = models.TextField('Описание', null=True, blank=True, max_length=1000)

    class Meta:
        verbose_name='Текущее состояние книги'
        verbose_name_plural='Текущие состояния книги'

    def __str__(self):
        return f'Состояние книги {self.book_obj.registr_number}'


class Person(models.Model):
    ''' Читатели библиотеки.'''
    last_name=models.CharField('Фамилия', max_length=50,  validators =[RegexValidator(regex='^[A-Za-zА-Яа-яЁё]+$', message='Введите только буквы.', code='invalid_name')])
    first_name=models.CharField('Имя', max_length=50,  validators =[RegexValidator(regex='^[A-Za-zА-Яа-яЁё]+$', message='Введите только буквы.', code='invalid_name')])
    surname=models.CharField('Отчество', max_length=50,null=True,blank=True,  validators =[RegexValidator(regex='^[A-Za-zА-Яа-яЁё]+$', message='Введите только буквы.', code='invalid_name')])
    passport=models.CharField('Номер паспорта', max_length=50, null=True,blank=True, unique=True)
    date_of_birth=models.DateField('Дата рождения')
    address=models.CharField('Адрес проживания', max_length=200, null=True,blank=True)
    mail=models.EmailField('Электронная почта', unique=True)
    agreement = models.BooleanField('Соглашение', default=True)
    status_person = models.BooleanField('Статус читателя', default=False)
    debt = models.DecimalField('Задолженность читателя', max_digits=7, decimal_places=2,  default=0)
    quantity_books = models.PositiveIntegerField('Выданные книги', default=0)

    class Meta:
        verbose_name = 'Читатель'
        verbose_name_plural = 'Читатели'
        ordering = ['last_name']

    def __str__(self):
        return f'{self.last_name},{self.date_of_birth}, выдано {self.quantity_books} книг'

    def get_debt(self):
        debt_sum = self.order_set.filter(status_order=True).aggregate(debt=Sum('debt_order'))['debt']
        self.debt = debt_sum or 0
        return self.debt


class Order(models.Model):
    '''Выдача книги.'''
    b_range = (
        (1, '1'),
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5'),
    )
    person = models.ForeignKey(Person, on_delete=models.PROTECT, verbose_name='Получатель книги')
    book_obj = models.ManyToManyField(BookObj, verbose_name='Книга для выдачи')
    distrib_date = models.DateField('Дата выдачи')
    pre_return_date = models.DateField('Дата возврата')
    pre_cost = models.DecimalField('Предварительная стоимость', max_digits=5, decimal_places=2, null=True,blank=True)
    quantity_books = models.PositiveIntegerField('Количество выданных книг', choices=b_range)
    debt_order = models.DecimalField('Задолженность по выдаче', max_digits=7, decimal_places=2, null=True,blank=True)
    status_order = models.BooleanField('Наличие задолженности', default=False)
    discount = models.DecimalField('Скидка', max_digits=3, decimal_places=2, null=True,blank=True)
    # mark = models.BooleanField( default=False)

    class Meta:
        verbose_name = 'Ордер'
        verbose_name_plural = 'Ордера'

    def __str__(self):
        return f'{self.person.last_name} {self.person.date_of_birth}  номер выдачи {self.pk}'


    def get_debt_order(self):
        days_use = date.today() - self.distrib_date
        days = days_use.days
        # days = '20'
        books_return = []
        for returnb in self.returnb_set.all():
            spisok_books = list(returnb.bookobj_set.all())
            for book in spisok_books:
                books_return.append(book)
        books = []
        for book_order in self.book_obj.all():
            if book_order in books_return:
                pass
            else:
                books.append(book_order)
        summa = sum(book.current_day_price for book in books)
        if int(days) <= 30:
            debt_order = round(float(summa) * int(days) * float(self.discount), 2)
        elif 30 < int(days) <= 120:
            penalty = round(float(summa) * float(self.discount) * 1.01 * (int(days) - 30), 2)
            cost = round(float(summa) * 30 * float(self.discount), 2)
            debt_order = cost + penalty
            print(cost)
        self.debt_order = debt_order
        return self.debt_order


class ReturnB(models.Model):
    b_range = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Выдача')

booklib/templates/add_book.html
{% extends 'basic.html' %}


{% block title %}
add_book
{% endblock %}

{% block content %}
<div class="forms-wrapper">
    <div class="form-container-book form-container">
        <form action="#toast" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ formB.as_p }}
            <input type="submit" value="Зарегистрировать" name="add_book" class="button_dr">
        </form>
        {% if formB.errors %}
        {% else %}
            <div id="toast" class="toast">Книга зарегистрирована</div>
        {% endif %}
    </div>
    <div class="form-container-genre">
        <p>Новый жанр</p>
        <form action="" method="POST">
            {% csrf_token %}
            {{ formG.as_p }}
            <input type="submit" value="Добавить" name="add_genre" class="button_genre">
        </form>
    </div>
 </div>
{% endblock %}

booklib/templates/add_person.html
{% extends 'basic.html' %}

{% block title %}
add_person
{% endblock %}

{% block content %}

<div class="form-container">
    <form action="#toast" method="POST">
        {% csrf_token %}
        {{ formP.as_p }}
        <input type="submit" value="Зарегистрировать" name="add_person" class="button_dr">
    </form>
    {% if formP.errors %}
    {% else %}
        <div id="toast" class="toast">Читатель зарегистрирован</div>
    {% endif %}
</div>

{% endblock %}

booklib/templates/basic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}BookLib{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
        <a href="{% url 'main' %}"><img src="{% static 'image/logo5.png' %}" alt="Логотип" class="logo"></a>
    </header>
    <div class="content">
        <div class="sidebar">
        <div class="button_container">
            <a href="{% url 'main' %}"  class="button-link">Начальная страница</a>
            <a href="{% url 'new_book' %}"  class="button-link" >Регистрация книги</a>
            <a href="{% url 'new_person' %}"  class="button-link" >Регистрация читателя</a>
            <a href="{% url 'give_book' %}"  class="button-link" >Выдача книги</a>
            <a href="{% url 'return_book' %}"  class="button-link" >Возврат книги</a>
            <form action="" method="POST">
                {% csrf_token %}
                <button type="submit" name="logout_button" class="button-link" style="background: #95735A;">Выйти из профиля</button>
            </form>
        </div>
        <!-- Вертикальный рейтинг -->
        {% if show_rating and list_books %}
        <div class="rating-list">
            <p style="text-align: center; font-weight: bold; font-size: 18px; color: #2C4058;">Топ популярных книг</p>
            {% for count, book in list_books %}
            <div class="rating-item">
                {% with book.fotoregistr_set.all as photos %}
                {% if photos %}
                    <img src="{{ photos.0.photo_book.url }}" alt="{{ book.title_rus }}" class="rating-photo">
                {% else %}
                    <div class="rating-photo placeholder">Нет фото</div>
                {% endif %}
                {% endwith %}
                <div class="rating-info">
                    <p class="book-title">{{ book.title_rus }}</p>
                    <!-- Звезды рейтинга -->
                        <div class="rating-stars">
                            {% for _ in "12345" %}
                                {% if forloop.counter <= book.rating %}
                                    <span class="star filled">&#9733;</span>
                                {% else %}
                                    <span class="star">&#9734;</span>
                                {% endif %}
                            {% endfor %}
                        </div>
                    <p>Прочитали: {{ count }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
   </div>
<!--Основной контент страницы -->
         <div class="main-content">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

booklib/templates/give_book.html
{% extends 'basic.html'%}
{% load static %}

{% block title %}Выдача книги{% endblock %}

{% block content %}
<div class="forms-wrapper-give">
<div class="form-container-give">
<form  action="#toast" method="POST">
    {% csrf_token %}
    <div class="form-row-person">
    <label for="person">Читатель</label>
    <select id="person" name="person">
        {% for person in persons %}
        <option value="{{ person.id }}">{{ person }}</option>
        {% endfor %}
    </select>
    </div>

    {% for i in "12345" %}
    <div class="form-row-book">
        <label for="book_{{ i }}">Книга{{ i }}</label>
        <select id="book_{{ i }}" name="book_{{ i }}" class="book-select">
            <option value="">--Выберите книгу--</option>
            {% for book in books %}
            <option value="{{ book.id }}">{{ book }}</option>
            {% endfor %}
        </select>

        <label for="bookobj_{{ i }}">Регистрационный номер</label>
        <select id="bookobj_{{ i }}" name="bookobj_{{ i }}" disabled>
            <option value="">--номер--</option>
        </select>
    </div>
    {% endfor %}

    <div class="form-row small-input">
    <label for="quantity_books">Количество книг</label>
    <input id="quantity_books" name="quantity_books" value="" readonly>
    </div>

    <div class="form-row small-input">
    <label for="discount">Скидка</label>
    <input id="discount" name="discount" value="" readonly>
    </div>

    <div class="form-row small-input">
    <label for="pre_return_date">Предварительная дата возврата</label>
    <input type="date" id="pre_return_date" name="pre_return_date" value="{{ pre_return_date }}" readonly>
    </div>

    <div class="form-row small-input">
    <label for="pre_cost" >Предварительная стоимость</label>
    <input type="number" id="pre_cost" name="pre_cost" value="" step="any" readonly>
    </div>

    <input type="submit" value="Зарегистрировать" name="give_book" class="button_dr">

</form>
<div id="toast" class="toast">Выдача зарегистрирована</div>
</div>

<div class="person-container">
    <label for="person_data">ФИО читателя</label>
    <select id="person_data" name="person_data">
        <option value="">--Выберите читателя--</option>
        {% for person in persons_all %}
        <option value="{{person.id}}">{{ person.last_name }} {{ person.first_name }} {{ person.surname }}</option>
        {% endfor %}
    </select>
    <div id="person_info"></div>
</div>
</div>

<script src="{% static 'js/formO.js' %}" defer></script>
<script> const getBookObjUrl = "{% url 'get_bookobj' %}"; </script>

<script src="{% static 'js/person_data.js' %}" defer></script>
<script>const getDataUrl = "{% url 'get_data' %}";</script>

{% endblock %}

booklib/templates/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="UTF-8">
<title>BOOKLIB</title>
<style>
    body { margin:0; padding:20px; background:#D4D5CF; font-family: "Palatino Linotype", "Book Antiqua", Palatino, serif; font-size: 16px; color: #2C4058; }
    .modal button, .btn { width: 240px; height: 33px; padding: 0; box-sizing: border-box;
        border: none;
        border-radius: 6px;
        background: #557A95;
        color: white;
        font-weight: bold;
        cursor: pointer;
        margin: 0px auto;
        text-align: center;
        line-height: 33px;
        display: block;
        font-family: "Palatino Linotype", "Book Antiqua", Palatino, serif; font-size: 16px;}
    .overlay { position:fixed; inset:0; background:rgba(0,0,0,0.6); display:flex; align-items:center; justify-content:center; }
    .modal { background:#fff; padding:24px; border-radius:12px; width:320px; box-shadow:0 6px 24px rgba(0,0,0,0.3); position:relative; }
    .modal h2 { text-align:center; margin-top:0; }
    .modal input { width:320px; padding:8px 10px; border:1px solid #ccc; border-radius:6px; box-sizing: border-box; font-size: 18px;
     font-family: "Palatino Linotype", "Book Antiqua", Palatino, serif;}
    .close { position:absolute; top:12px; right:16px; font-size:22px; color:#333; cursor:pointer; text-decoration:none; }
    .login-form { display:block; }
    .register-form { display:none; }
    #show-register:checked ~ .overlay .login-form { display:none; }
    #show-register:checked ~ .overlay .register-form { display:block; }

</style>
</head>
<body>

<!-- Чекбокс для переключения -->
<input type="checkbox" id="show-register" {% if show_register %} checked {% endif %}>

<div class="overlay">

    <!-- Форма входа -->
    <div class="modal login-form">
        <label for="show-register" class="close">&times;</label>
        <h2>Вход в BookLib</h2>
        <form method="POST">
            {% csrf_token %}
            {{ login_form.as_p }}
            {% if login_error %}<p style="color:red;">{{ login_error }}</p>{% endif %}
            <button type="submit" name="login_submit">Войти</button>
            <p style="text-align:center;"><label for="show-register" class="btn">Зарегистрироваться</label></p>
        </form>
    </div>

    <!-- Форма регистрации -->
    <div class="modal register-form">
        <label for="show-register" class="close">&times;</label>
        <h2>Добро пожаловать! Зарегистрируйтесь</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            {% if register_error %}<p style="color:red;">{{ register_error }}</p>{% endif %}
            <button type="submit" name="register_submit">Зарегистрироваться</button>
            <p style="text-align:center; margin-top:12px;">
                Уже есть аккаунт?
                <label for="show-register" class="btn">Войти</label>
            </p>
        </form>
    </div>

</div>

</body>
</html>

booklib/templates/main_page.html
{% extends 'basic.html' %}
{% load static %}

{% block title %}Список книг{% endblock %}
{% block content %}

<!-- Форма фильтрации -->
<form method="get" style="margin-bottom:20px; display:flex; gap:10px; align-items:center;">
    <input type="text" name="title" placeholder="Название книги" value="{{ query_title }}">
    <input type="text" name="author" placeholder="Автор" value="{{ query_author }}">
    <input type="text" name="genre" placeholder="Жанр" value="{{ query_genre }}">
    <input type="text" name="year" placeholder="Год" value="{{ query_year }}">
    <button type="submit" class="button_dr" style="width: 150px; background-color: #557A95;">Фильтровать</button>
    <a href="{% url 'main' %}" class="button_dr" style="width: 100px; text-decoration: none; background-color: #95735A;">Сбросить</a>
</form>

<div class="table-wrapper">
    <table class="styled-table" >
        <thead>
            <tr>
                <th>Фото</th>
                <th>Название</th>
                <th>Авторы</th>
                <th>Жанр</th>
                <th>Год</th>
                <th>Общее количество</th>
                <th>Доступное количество</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <td>{% with book.fotoregistr_set.all as photos %}
                        {% if photos %}
                            <img src="{{ photos.0.photo_book.url }}" alt="{{ book.title_rus }}" >
                        {% else %}
                            Нет изображения
                        {% endif %}
                        {% endwith %}
                </td>
                <td>{{ book.title_rus }}</td>
                <td>{% for author in book.author_set.all %}{{ author.name }}<br> {% endfor %}</td>
                <td>{% for genre in book.genres.all %}{{ genre.name_genre }}<br>{% endfor %}</td>
                <td>{{ book.year }}</td>
                <td>{{ book.general_quantity }}</td>
                <td>{{ book.current_quantity }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

booklib/templates/return.html
{% extends 'basic.html' %}
{% load static %}

{% block title %}
Возврат книг
{% endblock %}

{% block content %}
<div  class="form-container-book">
    <form action="" method="POST">
    {% csrf_token %}
    {{formR1.as_p}}
    <input type="submit" name="data_books" class="button_dr" value="Загрузить книги">
</form>

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{formR2.as_p}}
    <p style="color:red">{% if error %}{{ error }}{% endif %}</p>
    <input type="submit" name="calculate" class="button_dr" value="Оформить возврат">
</form>
    <p>Стоимость возврата: </p><br>

    <p>{% if return_cost == 0 %} 0 BYN {% else %}  {{ return_cost }}BYN {% endif %}</p><br>
    <form action="" method="POST">
        {% csrf_token %}
<input type="submit" name="return" class="button_dr" value="Завершить работу">
</form >

</div>

{% endblock %}